name: nu_finances
description: NuBank finance application concept

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: 3.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: 3.3.8
  # google_sign_in: 5.5.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/nulogo.png
    - assets/images/googleicon.png